version: 2
jobs:
  docker:
    - image: ubuntu
  build:
    steps:
      - checkout
      - run: docker build -t 4p00rv/py_server .

workflow:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
