version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t 4p00rv/py_server:${CIRCLE_TAG:-latest} .

  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run: | 
        docker login -u 4p00rv -p $DOCKERHUB_PASSWORD
        docker push 4p00rv/py_server:${CIRCLE_TAG}

workflows:
  version: 2
  build:
    jobs:
      - build
  tagged:
    jobs:
      - build
      - deploy

