version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t 4p00rv/py_server:${CIRCLE_TAG:-latest} .

  deploy:
    docker:
      - image: docker:17.05.0-ce-git
        username: 4p00rv
        password: $DOCKERHUB_PASSWORD
    steps:
      - run: docker push 4p00rv/py_server:${CIRCLE_TAG}

workflow:
  version: 2
  build:
    jobs:
      - build
  tagged:
    jobs:
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
